[package]
name = "ws"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
axum = { version = "0.6", features = ["ws"] }
futures = "0.3"
log = "0.4"
tokio = { version = "1.26", features = ["full"] }