[package]
name = "radiows"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
tokio = { version = "1.26", features = ["full"] }

common = { path = "../common" }
radio = { path = "../radio" }
ws = { path = "../ws" }
