[package]
name = "capybara"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.26"
image = "0.24.5"
# nokhwa = { version = "0.10.3", features = ["input-native"] }
rscam = "0.5.5"
tokio = { version = "1.26.0", features = ["full"] }

[profile.release]
lto = true
