[package]
name = "phototaker"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
image = { version = "0.24", features = ["webp-encoder"] }
log = "0.4"
tokio = { version = "1.26", features = ["full"] }